version: '3'
services:
  ring-home-assistant-bridge:
    container_name: ring-home-assistant-bridge
    image: ring-home-assistant-bridge:latest
    volumes:
      - ../ring-home-assistant-bridge/.env:/app/.env
      - ../ring-home-assistant-bridge/token:/app/token
    restart: unless-stopped
    ports:
      - "3123:3000"
