version: '3'
services:
  ring-home-assistant-bridge:
    container_name: ring-home-assistant-bridge
    image: ring-home-assistant-bridge:latest
    volumes:
      - ./.env:/app/.env
      - ./token:/app/token
    restart: unless-stopped
    ports:
      - "3123:3000"
